### PR TITLE
Switch to CMake

### PR DESCRIPTION
**Pull request by chouquette**
Hi,

This pull request switches the buildsystem to cmake, and tries to remove the need for private forks commited in the repo.
CMake eases the cross compilation part compared to qmake
If the system contains a libogg & libvorbis, we will now build using those.

I am not sure what's the way of hurting your builds the less, this seems like the best approach to me, as it should be transparent on your side, however, I think it would be best to remove the libogg & libvorbis folders.

If you'd prefer to switch to autotools, please let me know, that's definitely doable :)

### CODE REVIEW

**Comment by divideconcept** [comment]
Hi,

I'm not sure I understand why you renamed config.h to fluid_config.h. What's the point ?

I agree libogg and libvorbis can be removed but if libogg/vorbis aren't found/used, then you should not have this line in config.h: #define SF3_SUPPORT 1
So your cmake should probably act accordingly. Unless we define SF3_SUPPORT to 0 by default.
Otherwise fluid_defsfont.c won't build.

Regarding the build system itself, what do you think of having a cmake+the current .pro file ? The latter one is very straightforward for inclusion into my own Qt projects. I'm okay to maintain both the cmake and pro, if any file is added or removed from the project afterwards.

**Comment by chouquette** [comment]
Shipping a config.h as part of a library is a bad idea, since most (if not all) projects using autotools are using a config.h header internally. We had a similar problem with MLT++ (https://github.com/mltframework/mlt/pull/114) which was causing some issues with our internal config.h

config.h should be autogenerated, and indeed, those macros should be defined accordingly.
However, not finding the ogg/vorbis headers will make the build fail in any case. 
My choice would be to make libogg/libvorbis mandatory, and remove them from sources, but that seemed too intrusive of a change.

I honestly think keeping 2 build systems is a bad idea, and don't see the point in keeping the project file. CMake integrates nicely within QtCreator, and is much more powerfull than qmake. I'd argue that autotools is a better choice, but the QtCreator integration isn't that good (actually it's closer to inexistant)

**Comment by chouquette** [comment]
I forgot to mention that the config.h part is more of a workaround. In theory, none of your public headers should include it. The general rule is that config.h should be the first header included in all .c files, never in headers.

**Comment by divideconcept** [comment]
Yeah, old heritage from FluidSynth. I've removed as many unnecessary files as I could, but I could probably factor even more.

**Pull request merged**
