### PR TITLE
Minor fixups

### PR DESCRIPTION
**Pull request by JohannesKauffmann**
Fixed:
- some warnings
- a spelling mistake
- a bugfix (I think).

But let me know if the last commit is actually a bugfix, or if the user is supposed to do this beforehand:
```c
synth->sample_rate = sample_rate;
fluid_synth_set_sample_rate(synth, &sample_rate);
```

### CODE REVIEW

**Comment by divideconcept** [comment]
Have you tested your sample rate patch with 2 different sample rates and got expected results ?

**Comment by JohannesKauffmann** [comment]
No, I haven't tested it. The reason is that I have no idea how to use this library properly. After looking at the example (which was a pain to build on Windows!), I still have no idea how or what.

Reason for the change: GCC alerted me to an unused parameter, and after looking at the code some more, I thought that this should be the proper fix.

After reading online some more, it seems that `fluid_synth_set_sample_rate` is deprecated. Therefore, it seems better to just drop the last change. Let me know.

**Comment by divideconcept** [comment]
Yes, can you please drop the last change ? Then I'll merge.

**Comment by JohannesKauffmann** [comment]
Hi! A discussion section may be unneeded... It's very simple actually. FluidLite is used in VLC as a plugin essentially and enables all kinds of functionality I don't even know about. There is a build target in VLC which compiles all the third party dependencies these plugins rely on, so called contribs, and I noticed some warnings showing up when building FluidLite. VLC is built for a lot of different platforms, so we exercise different compiler (versions) when building the contribs. Thus, different warnings (and errors!) do show up from time to time.

I simply thought it'd be nice to clean up some of those warnings. That is my "use case".

**Comment by pedrolcl** [comment]
> FluidLite is used in VLC as a plugin
> That is my "use case".

OK. It is a totally valid use case. I didn't know that VLC was using FluidLite, but it totally makes sense (instead of using the whole FluidSynth library) because VLC  uses only a small part of FluidSynth: neither the MIDI or audio drivers, nor the MIDI file parser player/sequencer, because those functionalities are already provided by internal VLC implementations, so FluidLite can be a perfect fit in that project.

I only wanted to know about your difficulties to build FluidLite or the example project in Windows, so we can fix the build system, or documentation, or whatever.

**Comment by JohannesKauffmann** [comment]
@pedrolcl See issue #44.

**Pull request merged**
